# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
analyzer:
  errors:
    must_be_immutable: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Regras recomendadas
    - avoid_print # Evita o uso de print()
    - prefer_const_constructors # Prefere construtores constantes quando possível
    - unnecessary_new # Evita o uso do operador `new` ao criar objetos
    - prefer_final_fields # Prefere campos finais quando não são reatribuídos
    - omit_local_variable_types # Permite omitir tipos de variáveis locais
    - always_use_package_imports # Prefere usar importações de pacote em vez de relativas
    - prefer_single_quotes # Prefere aspas simples para strings
    - curly_braces_in_flow_control_structures
